[package]
name = "cipherfs-gui"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
cipherfs-core = { path = "../core" }
tauri = { version = "1.6", features = ["api-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.102"
rpassword = "7.5.2"
parking_lot = "0.12.5"

[target.'cfg(windows)'.dependencies]
winfsp = "0.1.0" 

[features]
# 這是 Tauri 生產環境編譯所必需的
custom-protocol = ["tauri/custom-protocol"]
